### PR TITLE
Added simple readme

### PR DESCRIPTION
**Pull request by Drakor**
Hi Kevin,

I've followed along with your Minecraft series so far and I've been really enjoying it. Since I assume you plan on adding more code here, I thought it might be handy to have a readme with some links so its a bit easier for people (like me) to follow along.

/Andreas

### CODE REVIEW

**Comment by Drakor** [comment]
Rebased, should be conflict free again.

**Comment by gisikw** [comment]
Hey, this is great! Sorry about the delay - I somehow wasn't watching this repo, so didn't get the notification >.<

Would you mind excluding the vim directive on the script itself? Want to make sure we're not messing with anyone's settings unwittingly :)

**Comment by Drakor** [comment]
Sorry for leaving it in there! I added it because my settings were initially different.

**Comment by gisikw** [comment]
No worries - and thanks again for the PR!

If it's helpful, you might consider tossing a project-level .vimrc in the directory. You'd want to add
```vim
set exrc
set secure
```
...into your main .vimrc, but then you could just toss the project-level one into a .gitignore :)

**Pull request merged**
